# Generated by Django 4.2.9 on 2025-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_size_remove_product_model_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
