# Generated by Django 4.2.9 on 2025-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
