# Generated by Django 4.2.9 on 2025-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_emergency_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
