# Generated by Django 4.2.9 on 2025-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_news_intro_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='daytime_look',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='evening_look',
            field=models.TextField(blank=True, null=True),
        ),
    ]
