# Generated by Django 4.2.9 on 2025-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_news_daytime_look_news_evening_look'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='news_articles', to='app.product'),
        ),
    ]
