# Generated by Django 4.2.9 on 2025-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('undertone', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], max_length=20)),
                ('recommended_colors', models.JSONField()),
                ('avoid_colors', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
