# Generated by Django 4.2.9 on 2025-06-16 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_skintone_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinUndertone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='skintone',
            name='avoid_colors',
        ),
        migrations.RemoveField(
            model_name='skintone',
            name='recommended_colors',
        ),
        migrations.RemoveField(
            model_name='skintone',
            name='undertone',
        ),
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='skintone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skintone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skin_tones/'),
        ),
        migrations.AlterField(
            model_name='skintone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='TryOnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
                ('skin_tone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skintone')),
                ('undertone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skinundertone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Try On Histories',
            },
        ),
        migrations.CreateModel(
            name='SkinTonePalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skin_palettes/')),
                ('skin_tone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skintone')),
                ('undertone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skinundertone')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='model_avatars/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('skin_tone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skintone')),
            ],
        ),
        migrations.CreateModel(
            name='ColorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_color', models.CharField(max_length=7)),
                ('color_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('undertone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skinundertone')),
            ],
        ),
        migrations.CreateModel(
            name='ColorAvoidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avoid_color', models.CharField(max_length=7)),
                ('color_name', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('undertone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.skinundertone')),
            ],
        ),
    ]
