# Generated by Django 4.2.9 on 2025-06-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_skinundertone_remove_skintone_avoid_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorrecommendation',
            name='undertone',
        ),
        migrations.RemoveField(
            model_name='modelavatar',
            name='skin_tone',
        ),
        migrations.RemoveField(
            model_name='tryonhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tryonhistory',
            name='skin_tone',
        ),
        migrations.RemoveField(
            model_name='tryonhistory',
            name='undertone',
        ),
        migrations.RemoveField(
            model_name='tryonhistory',
            name='user',
        ),
        migrations.RenameField(
            model_name='skintonepalette',
            old_name='color_code',
            new_name='color_hex',
        ),
        migrations.RemoveField(
            model_name='skintone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skintone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skintonepalette',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skintonepalette',
            name='undertone',
        ),
        migrations.AlterField(
            model_name='skintone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skintonepalette',
            name='skin_tone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='app.skintone'),
        ),
        migrations.DeleteModel(
            name='ColorAvoidance',
        ),
        migrations.DeleteModel(
            name='ColorRecommendation',
        ),
        migrations.DeleteModel(
            name='ModelAvatar',
        ),
        migrations.DeleteModel(
            name='SkinUndertone',
        ),
        migrations.DeleteModel(
            name='TryOnHistory',
        ),
    ]
