# Generated by Django 4.2.9 on 2025-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_colorrecommendation_undertone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintone',
            name='color_hex',
            field=models.CharField(default='#fce1d6', max_length=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SkinTonePalette',
        ),
    ]
