# Generated by Django 4.2.9 on 2025-06-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_skintone_color_hex_delete_skintonepalette'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinTonePalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(max_length=7)),
                ('skin_tone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='app.skintone')),
            ],
        ),
    ]
