# Generated by Django 4.2.9 on 2025-06-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_skintonepalette'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintonepalette',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
