# Generated by Django 4.2.9 on 2025-06-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_skintonepalette_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('formalwear', 'Formal Wear'), ('partywear', 'Party Wear'), ('casual', 'Casual')], default='formalwear', max_length=100),
        ),
    ]
