# Generated by Django 4.2.9 on 2025-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
