# Generated by Django 4.2.9 on 2025-06-19 13:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_legaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(config_name='default'),
        ),
    ]
