# Generated by Django 4.2.9 on 2025-06-19 13:52

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_legaldocument_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='slug',
            field=models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], max_length=20, unique=True),
        ),
    ]
