# Generated by Django 4.2.9 on 2025-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_legaldocument_content_alter_legaldocument_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], default='privacy', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
