# Generated by Django 4.2.9 on 2025-06-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintone',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('formalwear', 'Formal Wear'), ('partywear', 'Party Wear'), ('festiveCollection', 'Festive Collection'), ('rental', 'Rental Wear')], default='formalwear', max_length=100),
        ),
    ]
