# Generated by Django 4.2.9 on 2025-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_skintone_avatar_image_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skintone',
            name='avatar_image',
        ),
        migrations.AddField(
            model_name='skintone',
            name='base_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/base/'),
        ),
        migrations.AddField(
            model_name='skintone',
            name='clothing_mask',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/masks/'),
        ),
    ]
