# Generated by Django 4.2.9 on 2025-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintone',
            name='undertone',
            field=models.CharField(choices=[('cool', 'Cool'), ('warm', 'Warm'), ('neutral', 'Neutral')], default='neutral', max_length=50),
        ),
    ]
