# Generated by Django 4.2.9 on 2025-07-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_color_remove_skintone_undertone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='hex_code',
            new_name='color_hex',
        ),
    ]
