# Generated by Django 4.2.9 on 2025-07-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_hex_code_color_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
