# Generated by Django 4.2.9 on 2025-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_product_category_userselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintone',
            name='skin_mask',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/skin_masks/'),
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
